name: SAW-Puppeteer-Release erstellen

on:
  workflow_dispatch: # Manuelle Auslösung

permissions:
  contents: write 
  id-token: write 

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Abhängigkeiten installieren
        run: |
          mv puppeteer.json package.json
          npm install --package-lock-only --prefix .
          mv package.json puppeteer.json

      - name: Release-Version spezifizieren
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Code zu Executable bündeln
        run: npx pkg . --config puppeteer.json --targets node18-win-x64 --output saw-puppeteer.exe

      - name: Executable als Artefakt hochladen
        uses: actions/upload-artifact@v3
        with:
          name: saw-puppeteer
          path: saw-puppeteer.exe

      # Release erstellen
      - name: Release erstellen
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Puppeteer v${{ env.VERSION }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Release-Asset hochladen
      - name: Executable dem Release hinzufügen
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./saw-puppeteer.exe
          asset_name: saw-puppeteer.exe
          asset_content_type: application/octet-stream
